- hosts: master
  become: true
  tasks:
    - name: Read Terraform Outputs
      command: cat /tmp/tf_outputs.json
      register: tf_outputs_json

    - name: Parse Terraform Outputs
      set_fact:
        terraform_outputs: "{{ tf_outputs_json.stdout | from_json }}"

    - name: Configure Kops Cluster
      shell: |
        export KOPS_STATE_STORE=s3://{{ terraform_outputs.s3_bucket_name }}
        kops create cluster --name=k8s-cluster.k8s.local \
          --state=$KOPS_STATE_STORE \
          --vpc={{ terraform_outputs.vpc_id }} \
          --subnets={{ terraform_outputs.subnet_ids | join(',') }} \
          --zones=eu-north-1a,eu-north-1b \
          --node-count=2 \
          --node-size=t3.medium \
          --master-size=t3.medium \
          --dns-zone=k8s.local \
          --ssh-public-key=~/.ssh/id_rsa.pub

        kops update cluster k8s-cluster.k8s.local --yes
