name: "Terraform VPC Deployment"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -reconfigure -backend-config="bucket=terraform-state-sayantan" -backend-config="key=terraform.tfstate" -backend-config="region=eu-north-1"
        working-directory: environments/dev

      #- name: Terraform Plan VPC
     #   run: terraform plan
      #  working-directory: environments/dev

      - name: Terraform Apply VPC
        run: terraform apply -target=module.vpc -auto-approve
        working-directory: environments/dev

      - name: Fetch VPC ID
        id: vpc_output
        run: echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV
        working-directory: environments/dev

      - name: Store VPC ID in GitHub Environment
        run: echo "VPC_ID=${{ env.VPC_ID }}" >> $GITHUB_ENV
