name: Terraform VPC Deployment

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply VPC"
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1
      AWS_DEFAULT_REGION: eu-north-1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Terraform to Latest Version
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip jq
          TERRAFORM_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | jq -r .tag_name | sed 's/v//')
          curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform -version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Verify AWS Authentication
        run: aws sts get-caller-identity

      - name: Initialize Terraform
        run: |
          export TF_IN_AUTOMATION=1
          terraform init -input=false -reconfigure \
            -backend-config="bucket=my-terraform-bucket" \
            -backend-config="key=terraform/state.tfstate" \
            -backend-config="region=eu-north-1"

      - name: Terraform Plan VPC
        run: |
          export TF_IN_AUTOMATION=1
          terraform plan -target=module.vpc -out=tfplan -input=false
        working-directory: environments/dev

      - name: Terraform Apply VPC
        run: |
          export TF_IN_AUTOMATION=1
          terraform apply -target=module.vpc -auto-approve -input=false
        working-directory: environments/dev

      - name: Fetch VPC ID
        run: |
          echo "Fetching VPC ID..."
          VPC_ID=$(terraform output -raw vpc_id)
          echo "VPC_ID=$VPC_ID" >> $GITHUB_ENV

      - name: Store VPC ID in GitHub Environment
        run: echo "VPC_ID=${{ env.VPC_ID }}" >> $GITHUB_ENV

      - name: Post Configure AWS Credentials
        run: aws configure list

      - name: Post Checkout Repository
        run: echo "Pipeline completed!"
