name: Terraform VPC Deployment

on:
  push:
    branches:
      - main
    paths:
      - "modules/vpc/**"
      - "environments/dev/main.tf"

  workflow_dispatch:

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Apply VPC
        run: terraform apply -target=module.vpc -auto-approve
        working-directory: environments/dev

      - name: Fetch VPC ID
        run: echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV
        working-directory: environments/dev

      - name: Store VPC ID in S3 (Optional)
        run: aws s3 cp <(echo "$VPC_ID") s3://your-terraform-state-bucket/vpc_id.txt
