name: Terraform Security Groups Deployment

on:
  workflow_run:
    workflows: ["Terraform VPC Deployment"]
    types:
      - completed

jobs:
  terraform-security-groups:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Fetch VPC ID from S3
        run: export VPC_ID=$(aws s3 cp s3://your-terraform-state-bucket/vpc_id.txt -)

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Apply Security Groups
        run: terraform apply -target=module.security_groups -auto-approve -var="vpc_id=$VPC_ID"
        working-directory: environments/dev
