name: Terraform VPC Deployment

on:
  push:
    branches:
      - main
    paths:
      - "modules/vpc/**"
      - "environments/dev/main.tf"

  workflow_dispatch:

jobs:
  terraform-vpc:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        run: |
          sudo apt-get update && sudo apt-get install -y awscli

      - name: Verify AWS Authentication
        run: |
          aws sts get-caller-identity
