name: "Terraform & Kops Cluster Setup"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: AWS Authentication
        run: aws sts get-caller-identity

      - name: Change directory to environments/dev
        run: cd environments/dev

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq


      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_REGION

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Initialize Terraform
        run: terraform init
        working-directory: environments/dev

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: environments/dev

      - name: Debug Terraform Output
        run: |
          echo "Fetching Terraform Outputs..."
          terraform output -json
        working-directory: environments/dev

      - name: Fetch Terraform Outputs (Using jq)
        run: |
            echo "Fetching Terraform Outputs..."
            echo "KOPS_STATE_STORE=$(terraform output -json | jq -r '.kops_state_store.value // empty')" >> $GITHUB_ENV
            echo "VPC_ID=$(terraform output -json | jq -r '.vpc_id.value // empty')" >> $GITHUB_ENV
            echo "SUBNET_IDS=$(terraform output -json | jq -r '.subnet_ids.value | join(",") // empty')" >> $GITHUB_ENV
        working-directory: environments/dev


      - name: Debug Output Variables
        run: |
          echo "KOPS_STATE_STORE: $KOPS_STATE_STORE"
          echo "VPC_ID: $VPC_ID"
          echo "SUBNET_IDS: $SUBNET_IDS"

      - name: Deploy Kops Cluster
        run: sh deploy_kops.sh
        working-directory: scripts/

      - name: Refresh Terraform State
        run: terraform apply -refresh-only -auto-approve