name: "Terraform VPC Deployment"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init -backend-config="terraform-state-sayantan" -backend-config="key=terraform.tfstate" -backend-config="region=eu-north-1"

      - name: Terraform Apply VPC
        run: terraform apply -target=module.vpc -auto-approve -input=false -var="vpc_id="
        working-directory: environments/dev

      - name: Fetch VPC ID
        id: vpc_output
        run: echo "VPC_ID=$(terraform output -raw vpc_id)" >> $GITHUB_ENV

      - name: Store VPC ID in GitHub Environment
        run: echo "VPC_ID=${{ env.VPC_ID }}" >> $GITHUB_ENV
